root = "."
tmp_dir = "tmp"

[build]
# For Windows
bin = "./tmp/main.exe"
cmd = "go build -o ./tmp/main.exe ./cmd/web"
delay = 1000
exclude_dir = ["tmp", "vendor", "node_modules"]
include_ext = ["go", "tmpl", "html", "tpl", "css", "js"]
stop_on_error = true

[log]
time = false

[misc]
clean_on_exit = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"